name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.BOT_GITHUB_TOKEN }}
        issue-message: '@{user}! Thank you for contributing to my extension. Do you also like to sponsor this project?'
        pr-message: '@{user}! Thanks for your first pull request in this repostory. Would you like to sponsor me?'
